# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rails db:seed command (or created alongside the database with db:setup).
#
# Examples:
#
#   movies = Movie.create([{ name: 'Star Wars' }, { name: 'Lord of the Rings' }])
#   Character.create(name: 'Luke', movie: movies.first)
RestaurantCuisine.destroy_all
ItemAlertNote.destroy_all
AlertNote.destroy_all
Item.destroy_all
User.destroy_all
Restaurant.destroy_all
Cuisine.destroy_all

##Each line should have a distinct label u1, u2, u3...r1, r2...
#Users
u1 = User.create({first_name: "Tom", last_name: "Jerry", email: "tjerry@yahoo.com", phone: "2120193318", password: "123", username: "tomjerry"})

#Restaurants
r1 = Restaurant.create({name: "Le Pain Violet", street: "201 Baker Street", city: "New York", state:"NY", zip_code: "11201", phone: "9170092138", email: "hello@lpv.ny"})
r2 = Restaurant.create({name: "Nishikido Ramen Shop", street: "1982 Wavy Way", city: "Jersey City", state:"NJ", zip_code: "09182", phone: "6273019283", email: "ramen@nishikido.co"})
r3 = Restaurant.create({name: "Ristorante Di Formaggi", street: "384 Slippery Lane", city: "New York", state: "NY", zip_code: "10345", phone: "6462283053", email: "contact@diformaggi.org"})
r4 = Restaurant.create({name: "Smoke Shack", street: "2348 Brick Road", city: "New York", state: "NY", zip_code: "10228", phone: "7183492746", email: "burgers@smokeshack.com"})
r5 = Restaurant.create({name: "The Feel-Good Eatery", street: "2000 Green Lane", city: "Brooklyn", state: "NY", zip_code: "11385", phone: "6462584679", email: "namaste@feelgood.com"})
r6 = Restaurant.create({name: "The Roasted Bean", street: "835 Coco Road", city: "Brooklyn", state: "NY", zip_code: "11682", phone: "9172835028", email: "wakeup@roastedbean.com"})
r7 = Restaurant.create({name: "Mr. Chow Chow", street: "4583 Red Street", city: "Jersey City", state: "NJ", zip_code: "09234", phone: "62728472938", email: "chow@mrchowchow.com"})
r8 = Restaurant.create({name: "Go Loco For Taco", street: "2888 Picante Street", city: "New York", state: "NY", zip_code: "10347", phone: "7183708273", email: "hola@locofortaco.com"})
r9 = Restaurant.create({name: "Sweet Treats", street: "8274 Sugar Way", city: "New York", state: "NY", zip_code: "10287", phone: "7188273783", email: "hello@sweettreats.ny"})

#Cuisines
c1 = Cuisine.create({name: "French"})
c2 = Cuisine.create({name: "Modern"})
c3 = Cuisine.create({name: "Japanese"})
c4 = Cuisine.create({name: "Italian"})
c5 = Cuisine.create({name: "Burger"})
c6 = Cuisine.create({name: "Healthy"})
c7 = Cuisine.create({name: "Cafe"})
c8 = Cuisine.create({name: "Asian"})
c9 = Cuisine.create({name: "Mexican"})
c10 = Cuisine.create({name: "Bakery"})

#Restaurant Cuisine - link restaurant to cuisine(s)
rc1 = RestaurantCuisine.create({restaurant: r1, cuisine: c1})
rc2 = RestaurantCuisine.create({restaurant: r2, cuisine: c3})
rc3 = RestaurantCuisine.create({restaurant: r3, cuisine: c4})
rc4 = RestaurantCuisine.create({restaurant: r4, cuisine: c5})
rc5 = RestaurantCuisine.create({restaurant: r5, cuisine: c6})
rc6 = RestaurantCuisine.create({restaurant: r6, cuisine: c7})
rc7 = RestaurantCuisine.create({restaurant: r7, cuisine: c8})
rc8 = RestaurantCuisine.create({restaurant: r8, cuisine: c9})
rc9 = RestaurantCuisine.create({restaurant: r9, cuisine: c10})

#Items - restaurant field is a reference to one of the restaurant above. can mix them around - does not have to be one to one. a restaurant an be used multiple times
i1 = Item.create({name: "Blueberry Banana French Toast", image: "placeholder", restaurant: r1, price: 8.95})
i2 = Item.create({name: "Green Power Smoothie", image: "placeholder", restaurant: r1, price: 6.50})
i3 = Item.create({name: "Western Omelet", image: "placeholder", restaurant: r1, price: 7.95})
i4 = Item.create({name: "Chicken Miso Ramen", image: "placeholder", restaurant: r2, price: 11.95})
i5 = Item.create({name: "Cacio E Pepe", image: "placeholder", restaurant: r3, price: 17.95})
i6 = Item.create({name: "Smoked Bacon Cheeseburger", image: "placeholder", restaurant: r4, price: 10.95})
i7 = Item.create({name: "Truffle fries", image: "placeholder", restaurant: r4, price: 6.95})
i8 = Item.create({name: "Grilled Portobello Burger", image: "placeholder", restaurant: r5, price: 9.50})
i9 = Item.create({name: "Coco Berry Acai Bowl", image: "placeholder", restaurant: r5, price: 7.50})
i10 = Item.create({name: "California Green Salad", image: "placeholder", restaurant: r5, price: 10.50})
i11 = Item.create({name: "Banana Nut Bread", image: "placeholder", restaurant: r6, price: 4.50})
i12 = Item.create({name: "Nitro Cold Brew", image: "placeholder", restaurant: r6, price: 4.95})
i13 = Item.create({name: "Bacon Egg and Cheese Bagel", image: "placeholder", restaurant: r6, price: 4.95})
i14 = Item.create({name: "Avocado Toast", image: "placeholder", restaurant: r6, price: 6.95})
i15 = Item.create({name: "Pan Fried Shrimp Dumplings", image: "placeholder", restaurant: r7, price: 5.50})
i16 = Item.create({name: "Spicy Hand-Pulled Beef Noodles", image: "placeholder", restaurant: r7, price: 11.50})
i17 = Item.create({name: "Al Pastor Tacos", image: "placeholder", restaurant: r8, price: 6.00})
i18 = Item.create({name: "Guacamole With Chips", image: "placeholder", restaurant: r8, price: 5.00})
i19 = Item.create({name: "Skillet Cookie with Vanilla Ice Cream", image: "placeholder", restaurant: r9, price: 9.95})
i20 = Item.create({name: "1 Dozen Fresh Chocolate Chip Cookies", image: "placeholder", restaurant: r9, price: 9.95})

#AlertNotes - anything you want here
a1 = AlertNote.create({name: "Egg", alert_type: 'ALLERGEN'})
a2 = AlertNote.create({name: "Milk", alert_type: "ALLERGEN"})
a3 = AlertNote.create({name: "Tree Nuts", alert_type: "ALLERGEN"})
a4 = AlertNote.create({name: "Peanut", alert_type: "ALLERGEN"})
a5 = AlertNote.create({name: "Shellfish", alert_type: "ALLERGEN"})
a6 = AlertNote.create({name: "Gluten", alert_type: "ALLERGEN"})
a7 = AlertNote.create({name: "Soy", alert_type: "ALLERGEN"})

a8 = AlertNote.create({name: "Spicy", alert_type: "PREFERENCE"})
a9 = AlertNote.create({name: "Sweet", alert_type: "PREFERENCE"})
a10 = AlertNote.create({name: "Healthy", alert_type: "PREFERENCE"})
a11 = AlertNote.create({name: "Vegetarian", alert_type: "PREFERENCE"})

a12 = AlertNote.create({name: "Breakfast", alert_type: "MEAL_TYPE"})
a13 = AlertNote.create({name: "Lunch", alert_type: "MEAL_TYPE"})
a14 = AlertNote.create({name: "Dinner", alert_type: "MEAL_TYPE"})
a15 = AlertNote.create({name: "Quick", alert_type: "MEAL_TYPE"})
a16 = AlertNote.create({name: "Drink", alert_type: "MEAL_TYPE"})
a17 = AlertNote.create({name: "Snack", alert_type: "MEAL_TYPE"})


#ItemAlertNotes - an item can have many item alert notes they are basically tags/labels - but a new line for every alert
#blueberry banana french toast has allergens: egg(a1), milk(a2), wheat(a6) and is preference: sweet(a9) and MEAL_TYPE: breakfast(a10)
n1 = ItemAlertNote.create({item: i1, alert_note: a1})
n2 = ItemAlertNote.create({item: i1, alert_note: a2})
n3 = ItemAlertNote.create({item: i1, alert_note: a6})
n4 = ItemAlertNote.create({item: i1, alert_note: a9})
n5 = ItemAlertNote.create({item: i1, alert_note: a11})
n6 = ItemAlertNote.create({item: i2, alert_note: a2})
n7 = ItemAlertNote.create({item: i2, alert_note: a10})
n8 = ItemAlertNote.create({item: i2, alert_note: a11})
n9 = ItemAlertNote.create({item: i2, alert_note: a15})
n10 = ItemAlertNote.create({item: i2, alert_note: a16})
n11 = ItemAlertNote.create({item: i3, alert_note: a1})
n12 = ItemAlertNote.create({item: i3, alert_note: a2})
n13 = ItemAlertNote.create({item: i3, alert_note: a12})
n14 = ItemAlertNote.create({item: i4, alert_note: a1})
n15 = ItemAlertNote.create({item: i4, alert_note: a7})
n16 = ItemAlertNote.create({item: i4, alert_note: a14})
n17 = ItemAlertNote.create({item: i5, alert_note: a1})
n18 = ItemAlertNote.create({item: i5, alert_note: a2})
n19 = ItemAlertNote.create({item: i5, alert_note: a6})
n20 = ItemAlertNote.create({item: i5, alert_note: a11})
n21 = ItemAlertNote.create({item: i5, alert_note: a14})
n22 = ItemAlertNote.create({item: i6, alert_note: a6})
n23 = ItemAlertNote.create({item: i6, alert_note: a13})
n24 = ItemAlertNote.create({item: i6, alert_note: a14})
n25 = ItemAlertNote.create({item: i7, alert_note: a4})
n26 = ItemAlertNote.create({item: i7, alert_note: a6})
n27 = ItemAlertNote.create({item: i7, alert_note: a17})
n28 = ItemAlertNote.create({item: i8, alert_note: a6})
n29 = ItemAlertNote.create({item: i8, alert_note: a10})
n30 = ItemAlertNote.create({item: i8, alert_note: a11})
n31 = ItemAlertNote.create({item: i8, alert_note: a13})
n32 = ItemAlertNote.create({item: i8, alert_note: a14})
n33 = ItemAlertNote.create({item: i9, alert_note: a10})
n34 = ItemAlertNote.create({item: i9, alert_note: a11})
n35 = ItemAlertNote.create({item: i9, alert_note: a15})
n36 = ItemAlertNote.create({item: i10, alert_note: a4})
n37 = ItemAlertNote.create({item: i10, alert_note: a10})
n38 = ItemAlertNote.create({item: i10, alert_note: a11})
n39 = ItemAlertNote.create({item: i10, alert_note: a13})
n40 = ItemAlertNote.create({item: i11, alert_note: a1})
n41 = ItemAlertNote.create({item: i11, alert_note: a2})
n42 = ItemAlertNote.create({item: i11, alert_note: a3})
n43 = ItemAlertNote.create({item: i11, alert_note: a4})
n44 = ItemAlertNote.create({item: i11, alert_note: a6})
n45 = ItemAlertNote.create({item: i11, alert_note: a9})
n46 = ItemAlertNote.create({item: i11, alert_note: a12})
n47 = ItemAlertNote.create({item: i11, alert_note: a15})
n48 = ItemAlertNote.create({item: i11, alert_note: a17})
n49 = ItemAlertNote.create({item: i12, alert_note: a10})
n50 = ItemAlertNote.create({item: i12, alert_note: a15})
n51 = ItemAlertNote.create({item: i12, alert_note: a16})
n52 = ItemAlertNote.create({item: i13, alert_note: a1})
n53 = ItemAlertNote.create({item: i13, alert_note: a6})
n54 = ItemAlertNote.create({item: i13, alert_note: a12})
n55 = ItemAlertNote.create({item: i13, alert_note: a15})
n56 = ItemAlertNote.create({item: i14, alert_note: a6})
n57 = ItemAlertNote.create({item: i14, alert_note: a10})
n58 = ItemAlertNote.create({item: i14, alert_note: a11})
n59 = ItemAlertNote.create({item: i14, alert_note: a12})
n60 = ItemAlertNote.create({item: i14, alert_note: a17})
n61 = ItemAlertNote.create({item: i15, alert_note: a4})
n62 = ItemAlertNote.create({item: i15, alert_note: a6})
n63 = ItemAlertNote.create({item: i15, alert_note: a7})
n64 = ItemAlertNote.create({item: i15, alert_note: a17})
n65 = ItemAlertNote.create({item: i16, alert_note: a6})
n66 = ItemAlertNote.create({item: i16, alert_note: a7})
n67 = ItemAlertNote.create({item: i16, alert_note: a8})
n68 = ItemAlertNote.create({item: i16, alert_note: a13})
n69 = ItemAlertNote.create({item: i16, alert_note: a14})
n70 = ItemAlertNote.create({item: i17, alert_note: a6})
n71 = ItemAlertNote.create({item: i17, alert_note: a13})
n72 = ItemAlertNote.create({item: i17, alert_note: a14})
n73 = ItemAlertNote.create({item: i17, alert_note: a17})
n74 = ItemAlertNote.create({item: i18, alert_note: a4})
n75 = ItemAlertNote.create({item: i18, alert_note: a6})
n76 = ItemAlertNote.create({item: i18, alert_note: a7})
n77 = ItemAlertNote.create({item: i18, alert_note: a11})
n78 = ItemAlertNote.create({item: i18, alert_note: a17})
n79 = ItemAlertNote.create({item: i19, alert_note: a1})
n80 = ItemAlertNote.create({item: i19, alert_note: a2})
n81 = ItemAlertNote.create({item: i19, alert_note: a6})
n82 = ItemAlertNote.create({item: i19, alert_note: a9})
n83 = ItemAlertNote.create({item: i19, alert_note: a17})
n84 = ItemAlertNote.create({item: i20, alert_note: a1})
n85 = ItemAlertNote.create({item: i20, alert_note: a2})
n86 = ItemAlertNote.create({item: i20, alert_note: a6})
n87 = ItemAlertNote.create({item: i20, alert_note: a9})
n88 = ItemAlertNote.create({item: i20, alert_note: a17})